/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gameld_core_libqp */

#ifndef _Included_com_gameld_core_libqp
#define _Included_com_gameld_core_libqp
#ifdef __cplusplus
extern "C" {
#endif
#undef com_gameld_core_libqp_GP_GAME_END
#define com_gameld_core_libqp_GP_GAME_END 0L
#undef com_gameld_core_libqp_GP_GAME_PLAY
#define com_gameld_core_libqp_GP_GAME_PLAY 1L
#undef com_gameld_core_libqp_GP_ERROR
#define com_gameld_core_libqp_GP_ERROR 0L
#undef com_gameld_core_libqp_GP_BOMB
#define com_gameld_core_libqp_GP_BOMB 12L
/*
 * Class:     com_gameld_core_libqp
 * Method:    gpInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_libqp_gpInit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gameld_core_libqp_gpClear
  (JNIEnv *, jclass);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpGetState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_libqp_gpGetState
  (JNIEnv *, jclass);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpSetState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gameld_core_libqp_gpSetState
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpStart
 * Signature: (II[BI)V
 */
JNIEXPORT void JNICALL Java_com_gameld_core_libqp_gpStart
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpSetCards
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_com_gameld_core_libqp_gpSetCards
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpSetPlayedCards
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_com_gameld_core_libqp_gpSetPlayedCards
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpCanPlay
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_libqp_gpCanPlay
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpPlay
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_gameld_core_libqp_gpPlay
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpPass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gameld_core_libqp_gpPass
  (JNIEnv *, jclass);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpGetCurrentNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_libqp_gpGetCurrentNo
  (JNIEnv *, jclass);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpGetHandType
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_libqp_gpGetHandType
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpCardNum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_libqp_gpCardNum
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpGetCard
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_libqp_gpGetCard
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpCardPlayedNum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_libqp_gpCardPlayedNum
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gameld_core_libqp
 * Method:    gpGetCardPlayed
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_libqp_gpGetCardPlayed
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
