/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gameld_core_MyJni */

#ifndef _Included_com_gameld_core_MyJni
#define _Included_com_gameld_core_MyJni
#ifdef __cplusplus
extern "C" {
#endif
#undef com_gameld_core_MyJni_LDCORE_EVENT_QUIT
#define com_gameld_core_MyJni_LDCORE_EVENT_QUIT 1100L
#undef com_gameld_core_MyJni_LDCORE_EVENT_CONNECT
#define com_gameld_core_MyJni_LDCORE_EVENT_CONNECT 1101L
#undef com_gameld_core_MyJni_LDCORE_EVENT_DISCONNECT
#define com_gameld_core_MyJni_LDCORE_EVENT_DISCONNECT 1102L
#undef com_gameld_core_MyJni_LDCORE_EVENT_RECEIVE
#define com_gameld_core_MyJni_LDCORE_EVENT_RECEIVE 1103L
#undef com_gameld_core_MyJni_CORE_PARAM_LOG
#define com_gameld_core_MyJni_CORE_PARAM_LOG 1L
/*
 * Class:     com_gameld_core_MyJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gameld_core_MyJni_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_gameld_core_MyJni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_MyJni_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_gameld_core_MyJni
 * Method:    errorString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gameld_core_MyJni_errorString
  (JNIEnv *, jclass);

/*
 * Class:     com_gameld_core_MyJni
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_MyJni_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gameld_core_MyJni
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gameld_core_MyJni_clear
  (JNIEnv *, jclass);

/*
 * Class:     com_gameld_core_MyJni
 * Method:    log
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gameld_core_MyJni_log
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gameld_core_MyJni
 * Method:    connect
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_MyJni_connect
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_gameld_core_MyJni
 * Method:    send
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_MyJni_send
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_gameld_core_MyJni
 * Method:    sendXieyi
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_gameld_core_MyJni_sendXieyi
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_gameld_core_MyJni
 * Method:    setParam
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_gameld_core_MyJni_setParam
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
